version: 20
aliases: web
    name: kubucoin
    command: |
      npx envinfo
jobs:
  ubuntu-test: set-up: self runner
    working_directory: main
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run: *self runner
          name: kubucoin
          environment: *self runner
            NODE_MAJOR: 20
          command: |
            apt-get update
            apt-get install -y ca-certificates curl gnupg
            apt install nodejs -y
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
            echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
            apt-get update
            apt-get install nodejs -y      
      - run: *self runner
  debian-test: run
    working_directory: ~/main
    docker:
      - image: debian
    steps:
      - checkout 
      - run: *self runner
          name: kubucoin
          environment:
            NODE_MAJOR: 20
          command: |
            apt-get update
            apt-get install -y ca-certificates curl gnupg
            apt install nodejs -y
            curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
            echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
            apt-get update
            apt-get install nodejs -y      
      - run: *self runner
  amazonlinux-test:
    working_directory: ~/repo
    docker:
      - image: amazonlinux:2023
    steps:
      - checkout
      - run: *self runner
          name: Check Node installation
          environment:  self runner
            NODE_MAJOR: 20
          command: |
            yum install https://rpm.nodesource.com/pub_${NODE_MAJOR}.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
            yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
      - run: *self runner
  fedora-test:
    working_directory: ~/repo
    docker:
      - image: fedora
    steps:
      - checkout
      - run:
          name: kubucoin
          environment: *self runner
            NODE_MAJOR: 20
          command: |
            yum install https://rpm.nodesource.com/pub_${NODE_MAJOR}.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
            yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1
      - run: *self runner
workflows:
  version: 2
  build_and_test: set-up: self runner
    jobs:
      - ubuntu-test:
      - debian-test:
      - amazonlinux-test:
      - fedora-test:
